name: PHPStan
on: [workflow_dispatch, pull_request]
env:
  PLUGIN_CODE: EccubeMakerBundle
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eccube-versions: ['4.3']
        php-versions: [ '8.1', '8.2', '8.3' ]
        exclude:
          - eccube-versions: 4.2
            php-versions: 8.2
          - eccube-versions: 4.2
            php-versions: 8.3
          - eccube-versions: 4.3
            php-versions: 7.4
          - eccube-versions: 4.3
            php-versions: 8.0

    steps:
      - name: Checkout EC-CUBE
        uses: actions/checkout@v4
        with:
          repository: EC-CUBE/ec-cube
          ref: ${{ matrix.eccube-versions }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, mysql, intl, :xdebug
          tools: composer:v2

      - name: Initialize Composer
        uses: ./.github/actions/composer

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app/Plugin/${{ env.PLUGIN_CODE }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: PHPStan
        run: |
          composer require phpstan/phpstan --dev
          ./vendor/bin/phpstan analyze app/Plugin/${{ env.PLUGIN_CODE }} -c "app/Plugin/${{ env.PLUGIN_CODE }}/phpstan.neon" --error-format=github
